notifications:
  email: false
language: csharp
mono:
  - 5.12.0
solution: SimpleAdjustableFairings.sln
env:
  global:
  - PATH="${PATH}:${TRAVIS_BUILD_DIR}/bin"
  - VERSION="$(git describe --tags)"
  - KSP_VERSION="$(cat KSP_VERSION)"
  - KSP_DLL_PATH="/opt/ksp/assembly/${KSP_VERSION}"
  - BUILD_DIR="/var/tmp/simple_adjustable_fairings/build"
before_install:
  - sudo apt-get install python3-pip
install:
  - pip3 install awscli --upgrade --user
  - install-ksp-dlls
  - test -f "${KSP_DLL_PATH}/Assembly-CSharp.dll"
  - nuget restore ${TRAVIS_SOLUTION}
script:
  - msbuild /p:Configuration=Release /p:ReferencePath="${KSP_DLL_PATH}" ${TRAVIS_SOLUTION}
  - mkdir -pv "${BUILD_DIR}"
  - mkdir -pv "${BUILD_DIR}/assemble"
  - mkdir -pv "${BUILD_DIR}/assemble/SimpleAdjustableFairings"
  - mkdir -pv "${BUILD_DIR}/assemble/SimpleAdjustableFairings/GameData"
  - mkdir -pv "${BUILD_DIR}/package"
  - cp -r "${TRAVIS_BUILD_DIR}/GameData/SimpleAdjustableFairings" "${BUILD_DIR}/assemble/SimpleAdjustableFairings/GameData"
  - cp -v "${TRAVIS_BUILD_DIR}/README.md" "${TRAVIS_BUILD_DIR}/LICENSE" "${BUILD_DIR}/assemble/SimpleAdjustableFairings/"
  - cp -v "${TRAVIS_BUILD_DIR}/README.md" "${TRAVIS_BUILD_DIR}/LICENSE" "${BUILD_DIR}/assemble/SimpleAdjustableFairings/GameData/SimpleAdjustableFairings/"
  - (cd "${BUILD_DIR}/assemble/SimpleAdjustableFairings" && zip -rv "${BUILD_DIR}/package/SimpleAdjustableFairings.zip" .)
after_success:
  - mkdir -pv "${BUILD_DIR}/release"
  - cp -v "${BUILD_DIR}/package/SimpleAdjustableFairings.zip" "${BUILD_DIR}/release/SimpleAdjustableFairings_${VERSION}.zip"
deploy:
  - provider: releases
    skip_cleanup: true
    api_key: ${GITHUB_DEPLOY_TOKEN}
    file: ${BUILD_DIR}/release/*.zip
    file_glob: true
    name: "SimpleAdjustableFairings ${TRAVIS_TAG} for KSP ${KSP_VERSION}"
    on:
      tags: true
